# Generated by Django 5.2.5 on 2025-08-29 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('', 'Seleccione una ciudad'), ('LaPlata', 'La Plata'), ('Quilmes', 'Quilmes'), ('CABA', 'CABA'), ('Adrogue', 'Adrogué'), ('FlorencioVarela', 'Florencio Varela')], default='', max_length=50)),
                ('user', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('general_reason', models.TextField()),
                ('city', models.CharField(choices=[('', 'Seleccione una ciudad'), ('LaPlata', 'La Plata'), ('Quilmes', 'Quilmes'), ('CABA', 'CABA'), ('Adrogue', 'Adrogué'), ('FlorencioVarela', 'Florencio Varela')], default='', max_length=50)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.customer')),
                ('assigned_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seller')),
            ],
        ),
    ]
